project:
  name: wildfire-smoke-detection
  version: "1.0"

data:
  roboflow_workspace: "middle-east-tech-university"
  roboflow_project: "fire-and-smoke-detection-hiwia"
  roboflow_version: 2
  classes: ["fire", "smoke"]
  format: "yolov8"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  splits:
    train: 0.7
    val: 0.2
    test: 0.1

  image_size: 640
  data_yaml: "data/processed/data.yaml"

aws:
  bucket: "wildfire-smoke-detection"
  region: "eu-west-1"
  raw_prefix: "v2/data/raw"
  processed_prefix: "v2/data/processed"

training:
  # YOLOv8s: Obtuvimos mejores resultados que con la m, debido al cuello de botella del dataset
  model: "yolov8s.pt"
  best_model: "models/best.pt"
  epochs: 200
  batch_size: 32
  imgsz: 640
  patience: 50

mlflow:
  tracking_uri: "mlruns"
  experiment_name: "wildfire-smoke-detection"
  model_name: "wildfire-fire-smoke-detection"

serving:
  confidence_threshold: 0.25
